// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceSafari;

namespace SpaceSafari.Migrations
{
    [DbContext(typeof(Space_SafariContext))]
    [Migration("20190613204819_Space_Safari")]
    partial class Space_Safari
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SpaceSafari.Races", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Diet");

                    b.Property<string>("Home");

                    b.Property<string>("Language");

                    b.Property<string>("Mating");

                    b.Property<string>("Name");

                    b.Property<string>("Temperament");

                    b.HasKey("Id");

                    b.ToTable("AlienTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
